"""first

Revision ID: 9af8725264a4
Revises: 
Create Date: 2025-09-12 10:34:02.947776

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9af8725264a4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('hexcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('hexcode')
    )
    op.create_table('colorscheme',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('palette_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('hsla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('saturation', sa.Float(), nullable=False),
    sa.Column('light', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rgba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colorschemelink',
    sa.Column('scheme_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hexcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['hexcode'], ['color.hexcode'], ),
    sa.ForeignKeyConstraint(['scheme_name'], ['colorscheme.name'], ),
    sa.PrimaryKeyConstraint('scheme_name', 'hexcode')
    )
    op.create_table('userschemelink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_name'], ['colorscheme.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scheme_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userschemelink')
    op.drop_table('colorschemelink')
    op.drop_table('user')
    op.drop_table('rgba')
    op.drop_table('hsla')
    op.drop_table('colorscheme')
    op.drop_table('color')
    # ### end Alembic commands ###
